### PR TITLE
use dotenv in Laravel 5 config

### PR DESCRIPTION
**Pull request by ryanwinchester**

### CODE REVIEW

**Comment by arcanedev-maroc** [comment]
Nice, but my IDE did not know where to find this env() helper (https://github.com/illuminate/support/blob/master/helpers.php).

That's why i used the getenv() function based on the PHP dotenv repo (https://github.com/vlucas/phpdotenv)

**Comment by ryanwinchester** [comment]
It's here, https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/helpers.php#L595

**Comment by ryanwinchester** [comment]
I actually thought it was a dotenv thing since it was new in L5 along with dotenv, but it's just a new helper in L5, that let's you specify a default. It's a little cleaner than having to always use ternary operators.

**Comment by arcanedev-maroc** [comment]
Ok, i see, cannot fetch this helper ( https://github.com/laravel/framework/blob/5.0/src/Illuminate/Foundation/helpers.php) because is not included in composer autoload.
EDIT: My bad, now i can see it in my IDE :+1: 

Of course is a little bit cleaner, but the benefict of using this ternary operators is the backward compatibility with L4 and decoupled from L5.

Tnx for the link ( ^_^)b

**Pull request closed without merging**
